### ISSUE TITLE
Problemas para rodar na VM com Debian

### ISSUE THREAD

**Issue by Uchihinha** [cleitonleonel/bombcrypto-bot#1]
Olá, estou usando uma VM com Debian e estava procurando uma solução para multiaccounts nela e me deparei com este repositório, porém quando tento rodar o comando `python3 index.py` obtenho o seguinte erro:

![image](https://user-images.githubusercontent.com/50526061/148162824-3b1ffd2f-022b-4143-a83b-58f94a0eaa6e.png)

Podem me ajudar, por favor?

**Comment by cleitonleonel** [comment]
> Olá, estou usando uma VM com Debian e estava procurando uma solução para multiaccounts nela e me deparei com este repositório, porém quando tento rodar o comando `python3 index.py` obtenho o seguinte erro:
> 
> ![image](https://user-images.githubusercontent.com/50526061/148162824-3b1ffd2f-022b-4143-a83b-58f94a0eaa6e.png)
> 
> Podem me ajudar, por favor?

Seu erro está bem descrito aí "wmctrl not found".
Tente instalar com apt-get install wmctrl ou com sudo apt install wmctrl

**Comment by cleitonleonel** [comment]
> Olá, estou usando uma VM com Debian e estava procurando uma solução para multiaccounts nela e me deparei com este repositório, porém quando tento rodar o comando `python3 index.py` obtenho o seguinte erro:
> 
> ![image](https://user-images.githubusercontent.com/50526061/148162824-3b1ffd2f-022b-4143-a83b-58f94a0eaa6e.png)
> 
> Podem me ajudar, por favor?

https://command-not-found.com/wmctrl

**Comment by cleitonleonel** [comment]
Talvez ainda necessite de outro pacote Linux o xdotool, instale com apt-get install xdotool como descrito aqui:
https://command-not-found.com/xdotool

**Comment by Uchihinha** [comment]
Show, era isso mesmo, estava faltando o pacote, vlw irmão!
